### ISSUE TITLE
Support for mac version of the API

### ISSUE THREAD

**Issue by medcelerate** [TouchDesigner/TouchEngine-Windows#1]
I work on a few creative coding application hosts that only run on mac that would benefit from being able to use the touchengine API.

**Comment by mbechard** [comment]
Thanks, ya support is done pretty much, I think we are just working on a sample project for it.

**Comment by medcelerate** [comment]
Any updates on getting samples for this?

**Comment by bangnoise** [comment]
We'll post here as soon as we have something to share.

**Comment by medcelerate** [comment]
Any update on this, have a few applications we are developing that would really take advantage of this, but they are on the mac only.

**Comment by bangnoise** [comment]
https://github.com/TouchDesigner/TouchEngine-macOS
