### ISSUE TITLE
Sample program only loads grey screen

### ISSUE THREAD

**Issue by medcelerate** [TouchDesigner/TouchEngine-Windows#4]
I built the example application and loaded the sample tox included in the repo using both directx11 and 12 and all the applicaiton does is open a grey window. When I look at the debugger code I see it is not grabbing any of the exposed parameters from the TELinkGroups function. This issue is reproducible with other tox files.

**Comment by bangnoise** [comment]
Hi - the example does minimal error checking. If you set a breakpoint in `DocumentWindow::eventCallback()` what `TEEvent`s do you see? Do any of them have any results other than `TEResultSuccess`?

Which version of TouchDesigner do you have installed, and what license type?

**Comment by medcelerate** [comment]
It appears they all return TEresultsucess. I'm running TD 2022

**Comment by bangnoise** [comment]
What license type do you have?
Which TEEvents do you see in the eventCallback and in what order?
Perhaps place an assert there `assert(result == TEResultSuccess);` as that would be the most likely point for an error.

**Comment by medcelerate** [comment]
Version: 2022.33910
License: Non-Commercial

Events:
TEEventInstanceDidLoad

Asset function shows a TEResultNoKey for this function.

**Comment by keithlostracco** [comment]
Pretty sure you need to purchase a commercial license to use touch
engine...

**Comment by medcelerate** [comment]
That would appear to be it

**Comment by bangnoise** [comment]
Yep, as per the README, you currently need any of the paid license types to use TouchEngine.

We could improve error reporting in the example, we'll look to do that.

**Comment by medcelerate** [comment]
It would be useful to consider for dev work if you could use the
non-commercial license, but there is a limitation of time or a watermark of
sorts

**Comment by bangnoise** [comment]
If this is for a commercial project then reach out to support@derivative.ca explaining a bit more about what you're doing - otherwise I'm afraid this is how it is right now.

We are aware of the limitation and considering other options in the longer term.

**Comment by medcelerate** [comment]
In this case it's for an open source project creating touchengine as a
plug-in for another software. For the runtime users will definitely have to
buy a license.
