### ISSUE TITLE
'HANDLE': undeclared identifier in TEVulkan.h (on Windows)

### ISSUE THREAD

**Issue by keithlostracco** [TouchDesigner/TouchEngine-Windows#5]
Hello,

I'm getting 'HANDLE': undeclared identifier when including TEVulkan.h.  Maybe I'm missing something? 

The project compiles without issue after modifing TEVulkan.h to include Windows.h.

**Comment by bangnoise** [comment]
Hi - we rely on your setup for vulkan/vulkan.h - usually done by defining `VK_USE_PLATFORM_WIN32_KHR` at build time. You could also include Windows.h prior to including TEVulkan.h, or forward-declare `HANDLE`.

We're open to a better solution but we don't want to force an include for Windows.h for projects which are avoiding it or prefixing its inclusion with defines to limit it.

**Comment by keithlostracco** [comment]
Ah right, my mistake, I forgot to define VK_USE_PLATFORM_WIN32_KHR...

Thanks!
