### ISSUE TITLE
Possible bug with parameter types.

### ISSUE THREAD

**Issue by medcelerate** [TouchDesigner/TouchEngine-Windows#6]
I'm loading a known good tox file and with the latest lib and headers in the repo now it seems to be identifying the parameter types incorrectly. The below image shows the TestInt parameter I have exposed that is an int type in TD, but is carrying a double type associated with it, when previously it was an int type. It seems that other parameter types are shuffled as well.
![image](https://github.com/TouchDesigner/TouchEngine-Windows/assets/32549017/1db59dc0-1e1e-42e1-b272-d29c1e027d1d)

**Comment by bangnoise** [comment]
Can you duplicate the problem in the example app?

If not, make sure you have updated all of: TouchEngine.dll, TouchEngine.lib and the complete headers (from include/) in your own project, then clean and rebuild the project in Visual Studio.

**Comment by medcelerate** [comment]
So it appears that the DLL alongside the built integration was of a different version which caused the error. It could be useful if possible to have some header check for a DLL mismatch.
